### ISSUE TITLE
It's not possible to install the package via PIP

### ISSUE THREAD

**Issue by fdobrovolny** [shreyanshk/django-forwarded#2]
```
$ pip install django-forwarded
Collecting django-forwarded
  Using cached Django-Forwarded-0.0.2.tar.gz (5.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-o58uuvlh/django-forwarded_59b01ae41f874d20b7283d61105838ee/setup.py", line 7, in <module>
          version = subprocess.check_output(["git", "describe", "--tags"]).decode()[:-1]
        File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib64/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by shreyanshk** [comment]
Hello @fdobrovolny ,
Thanks for opening this issue.

I see that PyPi still has an old version of this package as I missed pushing the newest version.
Can you confirm if you can see a release tagged as 0.1.1 in this repo? If yes, can you please retry with that? Hopefully it would work better and after confirming that, I'll push the newest release (0.1.1) to PyPi.

Many thanks.

**Comment by fdobrovolny** [comment]
Hello @shreyanshk 

Yes. When I install it via:

```
pip install git+https://github.com/shreyanshk/django-forwarded@0.1.1
```

The instalation is succesfull.
